library(readr)
designtime <- read_csv("Downloads/IXuJf0mgEemFOA6Hm29iNA_88e719672fa44d0093d1d5a428d2e068_materials/designtime.csv")
designtime$Subject = factor(designtime$Subject) # convert to nominal factor
summary(designtime)
library(plyr)
ddply(designtime, ~ Tool, function(data) summary(data$Time))
ddply(designtime, ~ Tool, summarise, Time.mean=mean(Time), Time.sd=sd(Time))
hist(designtime[designtime$Tool == "Illustrator",]$Time) 
hist(designtime[designtime$Tool == "InDesign",]$Time)
shapiro.test(designtime[designtime$Tool == "Illustrator",]$Time)
shapiro.test(designtime[designtime$Tool == "InDesign",]$Time)
tt = aov(Time ~ Tool, data=designtime) 
shapiro.test(residuals(tt))
install.packages("car")
library(car)
leveneTest(Time ~ Tool, data=designtime, center=median)
install.packages("MASS")
library(MASS)
fitill = fitdistr(designtime[designtime$Tool == "Illustrator",]$Time, "lognormal")$estimate
fitin = fitdistr(designtime[designtime$Tool == "InDesign",]$Time, "lognormal")$estimate
ks.test(designtime[designtime$Tool == "Illustrator",]$Time, "plnorm", meanlog=fitill[1], sdlog=fitill[2], exact=TRUE)
ks.test(designtime[designtime$Tool == "InDesign",]$Time, "plnorm", meanlog=fitin[1], sdlog=fitin[2], exact=TRUE)
designtime$logTime = log(designtime$Time) # log transform
View(designtime) 
ddply(designtime, ~ Tool, summarise, logTime.mean=mean(logTime), logTime.sd=sd(logTime))
t.test(logTime ~ Tool, data=designtime, var.equal=TRUE)
install.packages("coin")
library(coin)
install.packages("survival")
library(survival)
wilcox_test(Time ~ Tool, data=designtime), distribution = "exact")
wt <- wilcox_test(Time ~ Tool, data = designtime, distribution = "exact", conf.int = TRUE)
